# GherkinExecutor Configuration
configuration:
  logIt: true
  inTest: false
  traceOn: false
  addLineToString: true
  searchTree: false
  oneDataFile: true
  spaceCharacters: '~'
  doNotCompare: "?DNC?"
  currentDirectory: ""
  featureSubDirectory: ""
  treeDirectory: "features/"
  startingFeatureDirectory: "features/"
  packageName: "gherkinexecutor"
  testSubDirectory: "gherkinexecutor/"
  dataDefinitionFileExtension: "cpp"
  testFramework: "gtest"
  addToPackageName: ""
  filterExpression: ""
  tagFilter: "@smoke"
  linesToAddForDataAndGlue:
    - "#include <iostream>"
  featureFiles:
    - "starting.featurex"



